### PR TITLE
Another attempt at d3 module bundling with webpack

### PR DESCRIPTION
**Pull request by ejfox**
still doesnt work tho

### CODE REVIEW

**Comment by ejfox** [comment]
@bradoyler do you know any way to correctly bundle d3 modules with webpack? I feel so dumb 

cc @enjalot

**Comment by ejfox** [comment]
@petulla do you know

**Comment by bradoyler** [comment]
```
import * as d3 from 'd3'
```

**Comment by bradoyler** [comment]
the proper way to use `d3-selection-multi` with imports?
Looks like the proper pattern is:
```
import {selection, select} from "d3-selection";
import "d3-selection-multi";
```

**Comment by bradoyler** [comment]
This seems related to https://github.com/d3/d3-selection-multi/issues/6
as `d3-selection-multi` doesn't actually export anything, it just overwrites the prototype for `d3.select()`

Also, you're not the only one: https://github.com/d3/d3-selection-multi/issues/11

**Pull request merged**
